name: simple python pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - run: python hello.py
  build:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: hello
          path: .
      
